a = input('Digite alguma coisa: ')
print('O tipo primitivo dest valor é ', type(a))
print('Só tem espaços? ', a.isspace())
print('É um numero? ', a.isnumeric())
print('É alfabético? ', a.isalpha())
print('É alfanumérico? ', a.isalnum())
print('É maiúsculo? ', a.isupper())
print('É minusculo? ', a.islower())
print('Esta capitalizada? ', a.istitle())
