times = ('Atlético-MG', 'Flamengo', 'Palmeiras', 'Fortaleza', 'Corinthians', 'Bragantino', 'Fluminense', 'América-MG', 'Atlético-GO', 'Santos', 'Ceará-SC', 'Internacional', 'São Paulo', 'Athletico-PR', 'Cuiabá', 'Juventude', 'Grêmio', 'Bahia', 'Sport Recife', 'Chapecoense')
print('='*50)
print('{:^50}'.format('Primeiros 5 colocados'))
print(times[:4])
print('='*50)
print('{:^50}'.format('Ultimos 4 colocados'))
print(times[-4:])
print('='*50)
print('{:^50}'.format('Ordem Alfabetica'))
print(sorted(times))
print('='*50)
print('{:^50}'.format('posição do time "Chapecoense" entre 20 times:'))
print(times.index('Chapecoense') + 1)
